### ISSUE TITLE
Exception grouping different than from raven-java

### ISSUE THREAD

**Issue by anujku** [agorapulse/grails-raven#4]
This was about grouping of exceptions. Currently, I see the grouping is based on the the exception message. But sometimes two exception messages could be similar with only Ids changed in the message. 

Case in point is these exceptions below -

<pre>
MissingMethodException occurred when processing request: [POST] /platformservices/zones/
No signature of method: net.nosegrind.restrpc.RestRPCService$_getParams_closure1.doCall() is applicable for argument types: (org.codehaus.groovy.grails.web.json.JSONObject) values: [[conceptId:16611, zones:[added:[], updated:[...], ...]]]
Possible solutions: doCall(java.lang.Object, java.lang.Object), call(), call([Ljava.lang.Object;), call(java.lang.Object), call(java.lang.Object, java.lang.Object), findAll(). Stacktrace follows:
</pre>

<pre>
MissingMethodException occurred when processing request: [POST] /platformservices/zones/
No signature of method: net.nosegrind.restrpc.RestRPCService$_getParams_closure1.doCall() is applicable for argument types: (org.codehaus.groovy.grails.web.json.JSONObject) values: [[conceptId:16610, zones:[added:[], updated:[...], ...]]]
Possible solutions: doCall(java.lang.Object, java.lang.Object), call(), call([Ljava.lang.Object;), call(java.lang.Object), call(java.lang.Object, java.lang.Object), findAll(). Stacktrace follows:
</pre>

So apart from Id in the message these exceptions are totally same. But they are still not grouped together. Logically I would say grouping here is correct. What do you think ? 

Looks like it is fixed in ravaen-java. The grails-plugin will need an update.

https://github.com/getsentry/raven-java/issues/125
https://github.com/getsentry/raven-java/issues/126

**Comment by benorama** [comment]
Hello,

I have a raven-java branch, which is a complete refactor to use the latest official raven-java lib:
https://github.com/agorapulse/grails-raven/tree/raven-java

But, when testing it locally, I've got the infamous NoClassDefFoundError , when starting some of our apps.
Some infamous class loading issues...
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sentryAppender': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [grails.plugins.raven.GrailsLog4jSentryAppender]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: net/kencochrane/raven/event/Event
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [grails.plugins.raven.GrailsLog4jSentryAppender]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: net/kencochrane/raven/event/Event
	... 4 more
Caused by: java.lang.NoClassDefFoundError: net/kencochrane/raven/event/Event
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethods(Class.java:1967)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at grails.plugins.raven.GrailsLog4jSentryAppender.<init>(GrailsLog4jSentryAppender.groovy:17)
```

The crazy thing is that some of our apps bootstrap without issues, some other don't.

**Comment by anujku** [comment]
I remember seeing this when I was trying out the raven-java lib in grails.

**Comment by benorama** [comment]
I've released version 6.0.0 based on the latest raven-java.
I've tested it on all our 8 Grails apps, and it worked on all of them, except one (with the class not found exception during bootstrapping).
It's not yet pushed/approved on our production servers, so use it with caution.
Could you give it a try locally on your app?

**Comment by anujku** [comment]
Sure I will try it out and let you know. Thanks for the quick response.

**Comment by anujku** [comment]
I am also seeing the class not found exceptions with 0.6.0 version.
<pre>

java.lang.NoClassDefFoundError: com/google/common/io/BaseEncoding
Error |
	at net.kencochrane.raven.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:107)
Error |
	at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:122)
Error |
	at net.kencochrane.raven.connection.AbstractConnection.send(AbstractConnection.java:78)
Error |
	at net.kencochrane.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:137)

</pre>

**Comment by anujku** [comment]
All right, the above error it seemed was due to the guava dependency in my project being not latest. I updated the dependency to fix that issue.
